### ISSUE TITLE
OpenAPI responses: section is missing for Discovery Docs methods that return no responses.

### ISSUE THREAD

**Issue by yuriylesyuk** [stackql/google-discovery-to-openapi#14]
**Describe the bug**

I tried to use a yaml openapi spec for google storage apis. it breaks a code generator I am trying to use with the following error report:

"OpenAPI definition has errors: 
attribute paths.'/b/{bucket}/acl/{entity}'(delete).responses is missing
attribute paths.'/b/{bucket}'(delete).responses is missing
attribute paths.'/channels/stop'(post).responses is missing
attribute paths.'/b/{bucket}/defaultObjectAcl/{entity}'(delete).responses is missing
attribute paths.'/b/{bucket}/notificationConfigs/{notification}'(delete).responses is missing
attribute paths.'/b/{bucket}/o/{object}/acl/{entity}'(delete).responses is missing
attribute paths.'/b/{bucket}/o/{object}'(delete).responses is missing
attribute paths.'/projects/{projectId}/hmacKeys/{accessId}'(delete).responses is missing"

If we zoom into the first delete method, it doesn't have the defined responses section.

https://github.com/stackql/stackql-provider-registry/blob/9e0360c6bbde208f33247ea1af1237085bb0f336/providers/src/googleapis.com/v00.00.00000/services/storage.yaml#L1569

That corresponds to the Google Discovery Document webpage:

https://cloud.google.com/storage/docs/json_api/v1/bucketAccessControls/delete#response

Which states:

"If successful, this method returns an empty response body."

According to the OpenAPI spec, the empty response body should be modelled by an absent responses'.<code>.content: key:

https://swagger.io/docs/specification/describing-responses/

"Empty Response Body
Some responses, such as 204 No Content, have no body. To indicate the response body is empty, do not specify a content for the response:

```
1.      responses:
2.        '204':
3.          description: The resource was deleted successfully.
```

**Expected behavior**

For any method that doesn't have responses defined and thus is omitted in the discovery document, a 'default' response without the content: key shall be generated.

**Comment by jeffreyaven** [comment]
I've just added in a __`204`__ empty response for all methods which do not return a response object.  The Google discovery docs only specify the response schema not response codes (inferred as `200` if the response exists).  The discovery docs do not specify http response codes (`200`, `204`, `403`, etc.).  See the storage spec [__`storage.zip`__](https://github.com/stackql/google-discovery-to-openapi/files/12444478/storage.zip) generated in the [`feature/refactor`](https://github.com/stackql/google-discovery-to-openapi/blob/feature/refactor/src/helper/functions.js#L166) branch this should get around your issue. If this works for you I can do a new build in the registry, let me know. Thanks!

**Comment by yuriylesyuk** [comment]
Thanks for being so responsive!

I can confirm that 204 is the right code to return. 

When I run:

```
$ gcloud storage buckets delete gs://$PROJECT_ID --verbosity=debug

...
DEBUG: Starting new HTTPS connection (1): storage.googleapis.com:443
DEBUG: https://storage.googleapis.com:443 "DELETE /storage/v1/b/qwiklabs-gcp-01-ed5bd98b06cb?alt=json HTTP/1.1" 204 0
  Completed 1/1    
...
```
as you can see, the debug verbosity level shows that google api return 204.

Thanks for generating a spec. I'll check it and will update.

**Comment by jeffreyaven** [comment]
Closed with https://github.com/stackql/google-discovery-to-openapi/pull/15
