### ISSUE TITLE
Invalid `type`: `any`

### ISSUE THREAD

**Issue by pinalbaldha** [stackql/google-discovery-to-openapi#17]
**Describe the bug**
Google Rest's Json Schema includes "type": "any". 
This is `any` type is not supported in OpenAPI: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#data-types
 

**To Reproduce**
File: https://github.com/stackql/stackql-provider-registry/blob/dev/providers/src/googleapis.com/v00.00.00000/services/aiplatform.yaml#L4561
```
        metadata:
          description: Required. Additional information about the Dataset.
          type: any
```

**Expected behavior**
I am not sure whether to keep empty or to keep object type.

```
        metadata:
          description: Required. Additional information about the Dataset.
```
OR

```
        metadata:
          description: Required. Additional information about the Dataset.
          type: object
```

**Comment by jeffreyaven** [comment]
I would take the first option and avoid specificity as the OpenAPI spec does not have a direct representation for the `any` type as the Google discovery doc format (which is a variant of JSON Schema) does.  You could do something expansive with polymorphism like `anyOf`.  But an option when the `any` type is found could be to do the following:

```yaml
metadata:
  description: Required. Additional information about the Dataset.
  x-original-type: any
```
> I would only do this when the type is changed or unsupported otherwise it would bloat the documents...

Currently the `type` is passed through without inspection, our program [`stackql`](https://github.com/stackql/stackql), which consumes these docs, ignores the `any` type.  What do you think?

**Comment by pinalbaldha** [comment]
Yes, Option 1 is suitable.

For now, custom extension `x-original-type` is not required. 

Agree, ignoring not supported types will yield the same result as Option 1.
