### ISSUE TITLE
Need more documentation, cannot run on OSX

### ISSUE THREAD

**Issue by stcalica** [stackql/google-discovery-to-openapi#22]
**Describe the bug**
Can't seem to install from /bin or get to run. 
Also, some more how-to use to be helpful. 

**To Reproduce**
1. git clone repo 
2. `cd google-discovery-to-openapi`
3. `npm install bin/google-discovery-to-openapi.mjs generate googleapis.com`

Ends up failing and saying cannot be found, 
even tried to do `./bin/google-discovery-to-openapi.mjs`

```
kyle@Kyles-MacBook-Pro google-discovery-to-openapi % npm install bin/google-discovery-to-openapi.mjs generate googleapis.com
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/googleapis.com - Not found
npm ERR! 404
npm ERR! 404  'googleapis.com@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kyle/.npm/_logs/2024-03-07T00_12_18_940Z-debug.log
kyle@Kyles-MacBook-Pro google-discovery-to-openapi % npm install ./bin/google-discovery-to-openapi.mjs generate googleapis.com
npm ERR! code ENOLOCAL
npm ERR! Could not install "bin/google-discovery-to-openapi.mjs" as it is not a directory and is not a file with a name ending in .tgz, .tar.gz or .tar

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kyle/.npm/_logs/2024-03-07T00_12_36_038Z-debug.log
kyle@Kyles-MacBook-Pro google-discovery-to-openapi %
```

**Expected behavior**
To install and script to run

**Desktop (please complete the following information):**
 - OS: MAC OSX - MacBook Pro - M1

**Comment by jeffreyaven** [comment]
hey @stcalica try `npm install; bin/google-discovery-to-openapi.mjs generate googleapis.com`

**Comment by stcalica** [comment]
Okay for some reason my bin had packages in it, maybe I ran the code in there somehow. 

Other thing I had to fix was `sudo` and also add `node`, as I couldn't just call `bin/google-discovery-to-openapi.mjs generate googleapis.com` 

I'd add that to the documentation maybe?

**Comment by jeffreyaven** [comment]
Thanks @stcalica I can add this, let me know how you go with this

**Comment by stcalica** [comment]
It went perfect thank you!

**Comment by jeffreyaven** [comment]
have you checked out our flagship project @stcalica [__stackql__](https://github.com/stackql/stackql), its a SQL based API client for queries and mutations, we are looking for contributors and feedback, have a 👀, give us a ⭐ if you can, 🙏
