### ISSUE TITLE
Cloud Commerce Partner Procurement API

### ISSUE THREAD

**Issue by sandeep-khanna** [stackql/google-discovery-to-openapi#23]
Can this utility be used to convert the [Google Cloud Commerce Partner Procurement API](https://cloud.google.com/marketplace/docs/partners/commerce-procurement-api/reference/rest) Discovery document (JSON) to the OpenAPI (YAML)?

The ultimate goal is to generate a Java client library and possibly using something like [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator#openapi-generator).

**Comment by jeffreyaven** [comment]
Yes it can, we can do this for you, will update this ticket when complete

**Comment by jeffreyaven** [comment]
hi @sandeep-khanna, this service was not in the root google discovery doc, but I have extended support for services outside the root doc, see [here](https://github.com/stackql/google-discovery-to-openapi/blob/main/src/commands/generate.js#L165), I have attached an example I just generated [cloudcommerceprocurement.zip](https://github.com/stackql/google-discovery-to-openapi/files/15367468/cloudcommerceprocurement.zip)  

Ill add this to the next [`google` provider](https://google.stackql.io/providers/google/) version, ⭐ our main repo [__`stackql`__](https://github.com/stackql/stackql) if you can!
